/**
 * @author  Alena Fisher
 * 5/7/2024
 */

// Importing all necessary classes
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.ListIterator;

public class Court_GUI extends javax.swing.JFrame {
    /**
     * This is the main entry point of this class file
     * This file allows for the creation, updating, display, and removal of basketball and volleyball games at the sports club
     */
    
    // Delcaring varibles
    private static GameSchedule courtSchedule;
    private static Teams volleyballTeams;
    private static Teams basketballTeams;
    private static String fileLocation = "Court.dat";

    public Court_GUI() {
        /**
         * This constructor initializes all components for the file
         */
        initComponents();
        // Initializing the lists for the game schedule and the volleyball and basketball teams
        courtSchedule = new GameSchedule();
        volleyballTeams = new Teams();
        basketballTeams = new Teams();
        
        Team milwaukeeBucks = new Team("Milwaukee Bucks", "Doc Rivers", "Milwaukee", "Wisconsin", "17");
        basketballTeams.addTeam(milwaukeeBucks);
        
        Team bostonCeltics = new Team("Boston Celtics", "Joe Mazzulla", "Boston", "Massachusetts", "17");
        basketballTeams.addTeam(bostonCeltics);
        
        Team minnesotaTimberwolves = new Team("Minnesota Timberwolves", "Chris Finch", "Minneapolis", "Minnesota", "17");
        basketballTeams.addTeam(minnesotaTimberwolves);
        
        Team dallasMavericks = new Team("Dallas Mavericks", "Jason Kidd", "Dallas", "Texas", "17");
        basketballTeams.addTeam(dallasMavericks);
        
        Team womensTeam = new Team("Women's National Volleyball Team", "Karch Kiraly", "Colorado Springs", "Colorado", "40");
        volleyballTeams.addTeam(womensTeam);
        
        Team mensTeam = new Team("Men's National Volleyball Team", "John Speraw", "Colorado Springs", "Colorado", "30");
        volleyballTeams.addTeam(mensTeam);
        
        // Compiling each team's information to a string to be displayed
        String s = "";
            
        // Linked list to receive all volleyball teams and their information
        LinkedList<Team> team = volleyballTeams.getTeam();
        LinkedList<Team> teams = volleyballTeams.getTeams();
          
        // Iterators to iterate through each list
        ListIterator<Team> iterator = teams.listIterator();
        ListIterator<Team> iter = team.listIterator();
            
        // Linked lists to receive all basketball teams and their information
        LinkedList<Team> Team = basketballTeams.getTeam();
        LinkedList<Team> Teams = basketballTeams.getTeams();
            
        // Iterators to iterate through each list
        ListIterator<Team> Iterator = Teams.listIterator();
        ListIterator<Team> Iter = Team.listIterator();

        // While loop to search through the list of volleyball teams
        while(iterator.hasNext()) {
        Team j = iterator.next();
            // While loop to search through the list of information for each team and print it out
            while(iter.hasNext()) {
                Team l = iter.next();
                // Printing out each team's information
                s += "Team: " + l.getTeamName() + "\nCoach: " + l.getCoach() + "\nCity: " + l.getCity() + "\nState: " + l.getState() + "\nPlayers " + l.getNumOfPlayers() + "\n";
                txtTeamDisplay.setText(s);
            }
        }
           
        // While loop to search through the list of basketball teams
        while(Iterator.hasNext()) {
            Team j = Iterator.next();
            // While loop to search through the list of information for each team and print it out
            while(Iter.hasNext()) {
                Team l = Iter.next();
                // Printing out each team's information
                s += "Team: " + l.getTeamName() + "\nCoach: " + l.getCoach() + "\nCity: " + l.getCity() + "\nState: " + l.getState() + "\nPlayers " + l.getNumOfPlayers() + "\n";
                txtTeamDisplay.setText(s);
            }
            }
    }
    
    public Court_GUI(Club aClub) {
        /**
         * This constructor receives 'aClub' as an explicit parameter and creates an object for the window to be opened
         */
        this();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTeam2 = new javax.swing.JTextField();
        txtTeam1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtGameTime = new javax.swing.JTextField();
        txtGameDate = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btntScheduleGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourtSchedule = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTeamDisplay = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();

        setTitle("Court");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Team 1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Team 2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel1.add(txtTeam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));
        jPanel1.add(txtTeam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, -1));

        jLabel4.setText("Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("Time:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setText("Location (North/South gym):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, -1));
        jPanel1.add(txtGameTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, -1));
        jPanel1.add(txtGameDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Schedule Game"));
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 300));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Volleyball Teams\n- Men's National\nVolleyball Team\n- Women's National\nVolleyball Teams\n\nBasketball Teams\n- Milwaukee Bucks\n- Boston Celtics\n- Minnesota \nTimberwolves\n- Dallas Mavericks");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Teams"));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 300));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        btntScheduleGame.setText("Schedule");
        btntScheduleGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntScheduleGameActionPerformed(evt);
            }
        });
        jPanel1.add(btntScheduleGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Court.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Schedule Game", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCourtSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team 1", "Team 2", "Date", "Team ", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCourtSchedule);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Court.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        jTabbedPane1.addTab("Game Information", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTeamDisplay.setEditable(false);
        txtTeamDisplay.setColumns(20);
        txtTeamDisplay.setRows(5);
        jScrollPane5.setViewportView(txtTeamDisplay);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 300));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Court.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));
        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Team Information", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 520, 360));

        setSize(new java.awt.Dimension(541, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntScheduleGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntScheduleGameActionPerformed
           /**
            * This method collects the information from the user and creates either a volleyball or basketball game that is stored
            * in the court's game schedule
            */
        
            // Gathering the input from the user entered into the text fields
            String team1 = txtTeam1.getText();
            String team2 = txtTeam2.getText();
            String gameDate = txtGameDate.getText();
            String gameTime = txtGameTime.getText();
            String location = txtLocation.getText();
            
            // Creating the game and adding it to the game schedule
            Game game = new Game(team1, team2, gameDate, gameTime, location);
        
            // Testing if any of the text fields are left empty by the user
            if(txtTeam1.getText().isEmpty() || txtTeam2.getText().isEmpty() || txtGameDate.getText().isEmpty() || txtGameTime.getText().isEmpty() || txtLocation.getText().isEmpty()) {
                // Message to the user if any of the text fields were not filled out
                JOptionPane.showMessageDialog(this, "Enter all fields");
            }
       
            // If all the fields are filled out, the information is gathered and placed into a row in the table
            else {
                String[] row = {txtTeam1.getText(), txtTeam2.getText(), txtGameDate.getText(), txtGameTime.getText(), txtLocation.getText()};
                // Table to display the games to the user
                DefaultTableModel model = (DefaultTableModel)tblCourtSchedule.getModel();
                // Information is added to the table
                model.addRow(row);
            
                // Message to the user that the game scheduling was successful
                JOptionPane.showMessageDialog(this, "Game added");
            }
    }//GEN-LAST:event_btntScheduleGameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        /**
         * This method calls the 'clearFields' method to reset all text fields to be empty
         */
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Table to display the games
        DefaultTableModel model = (DefaultTableModel)tblCourtSchedule.getModel();
        // Array list to store the data from the table
        ArrayList<String> tableData = new ArrayList<>();
        
        // For loop to gather the information from the table row by row and store it in the array list
        for(int i = 0; i < model.getRowCount(); i++) {
            String team1 = model.getValueAt(i, 0).toString();
            String team2 = model.getValueAt(i, 1).toString();
            String gameDate = model.getValueAt(i, 2).toString();
            String gameTime = model.getValueAt(i, 3).toString();
            String location = model.getValueAt(i, 4).toString();
            
            // Data is compiled and added to the array list
            String row = team1 + "," + team2 + "," + gameDate + "," + gameTime + "," + location;
            tableData.add(row);
            
            // try-catch to attempt storing the information in the dat file
            try {
                // Opening the file
                FileOutputStream file = new FileOutputStream("Court.dat");
                ObjectOutputStream output = new ObjectOutputStream(file);
                
                // Storing the information in the file
                output.writeObject(tableData);
                
                // Closing the files
                output.close();
                file.close();
            }
            // If storing the information is unsuccessful, it catches the error
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // try-catch to place the information stored in the file into the tables
        try { 
            // Opening the file
            FileInputStream file = new FileInputStream("Court.dat");
            ObjectInputStream input = new ObjectInputStream(file);
            // Adding the information to the array list
            ArrayList<String> tableData = (ArrayList<String>)input.readObject();
        
            // Closing the files
            input.close();
            file.close();
        
            // Table for displaying game schedule
            DefaultTableModel model = (DefaultTableModel)tblCourtSchedule.getModel();
            // Adding the information into the table
            for(int i = 0; i < tableData.size(); i++) {
                String[] row = tableData.get(i).split(",");
                model.addRow(row);
            }
        }
        // If placing the information is unsuccessful, it catches the error
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void clearFields() {
        /**
         * This method sets all text fields to be empty so the user can schedule another game if they wish 
         */
        txtTeam1.setText("");
        txtTeam2.setText("");
        txtGameDate.setText("");
        txtGameTime.setText("");
        txtLocation.setText("");
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Court_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Court_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Court_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Court_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Court_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btntScheduleGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tblCourtSchedule;
    private javax.swing.JTextField txtGameDate;
    private javax.swing.JTextField txtGameTime;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTeam1;
    private javax.swing.JTextField txtTeam2;
    private javax.swing.JTextArea txtTeamDisplay;
    // End of variables declaration//GEN-END:variables
}
