/**
 * @author  Alena Fisher
 * 5/7/2024
 */

// Importing all necessary classes
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Gym_GUI extends javax.swing.JFrame {  
    /**
     * This is the main entry point of this class file
     * This file allows for the creation, updating, display, and removal of baseball and softball games at the sports club
     */
    
    // Delcaring variblesstatic GameSchedule gymSchedule;
    private static Teams powerliftingTeams; 
    private static String fileLocation = "Gym.dat";   
    private static GameSchedule gymSchedule;
    
    public Gym_GUI() {
        /**
         * This constructor initializes the components for the file, the gym schedule, and the powerlifting teams
         */
        initComponents();
        gymSchedule = new GameSchedule();
        powerliftingTeams = new Teams();
        
        // Adding teams to the list
        Team charlotteLifters = new Team("The Charlotte Lifters", "Jinisha Sohal", "Charlotte", "North Carolina", "12");
        powerliftingTeams.addTeam(charlotteLifters);
        
        Team legacy = new Team("Legacy", "Matthew Octaviano", "Wilmington", "North Carolina", "12");
        powerliftingTeams.addTeam(legacy);
        
        Team cobras = new Team("Cobra Powerlifting", "Tucker Thompson", "Denver", "North Carolina", "12");
        powerliftingTeams.addTeam(cobras);
        
        Team blueDevils = new Team("Blue Devil Barbells", "Alexia Bensoussan", "Durham", "North Carolina", "12");
        powerliftingTeams.addTeam(blueDevils);
        
        Team unleashed = new Team("UNLEASHED", "Dylan Caylor", "Wilmington", "North Carolina", "12");
        powerliftingTeams.addTeam(unleashed);
        
        String s = "";
        
        // Linked lists to receive the powerlifting teams and all their information
        LinkedList<Team> team = powerliftingTeams.getTeam();
        LinkedList<Team> teams = powerliftingTeams.getTeams();
          
        // Linked lists to iterate through the list of teams and their information
        ListIterator<Team> iterator = teams.listIterator();
        ListIterator<Team> iter = team.listIterator();

        // While loop to search through the list of teams
            while(iterator.hasNext()) {
            Team j = iterator.next();
            // While loop to search through the list of information for each team and print it out
            while(iter.hasNext()) {
                Team l = iter.next();
                s += "Team: " + l.getTeamName() + "\nCoach: " + l.getCoach() + "\nCity: " + l.getCity() + "\nState: " + l.getState() + "\nPlayers " + l.getNumOfPlayers() + "\n";
                txtDisplayTeams.setText(s);
            }
        }
    }

    public Gym_GUI(Club aClub) {
        /**
         * This constructor receives 'aClub' as an explicit parameter and creates an object for the window to be opened
         */
        this();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddComp = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        txtLocation = new javax.swing.JTextField();
        txtCompetitionTime = new javax.swing.JTextField();
        txtCompetitionDate = new javax.swing.JTextField();
        txtTeam2 = new javax.swing.JTextField();
        txtTeam1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnClearFields = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDisplayComps = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDisplayTeams = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Gym");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddComp.setText("Schedule");
        btnAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Charlotte Lifters\n\nLegacy\n\nCobra Powerlifting\n\nBlue Devil Barbells\n\nUNLEASHED\n\n");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Teams"));
        jPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 230, 320));

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        jPanel1.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, -1));
        jPanel1.add(txtCompetitionTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, -1));
        jPanel1.add(txtCompetitionDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));
        jPanel1.add(txtTeam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));
        jPanel1.add(txtTeam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        jLabel6.setText("Location:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel5.setText("Competition Time:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setText("Competition Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setText("Team 2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel1.setText("Team 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Schedule Competition"));
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gym.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jTabbedPane1.addTab("Add Competition", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDisplayComps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team 1", "Team 2", "Date", "Time", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDisplayComps);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 390));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gym.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("Competition Information", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDisplayTeams.setEditable(false);
        txtDisplayTeams.setColumns(20);
        txtDisplayTeams.setRows(5);
        jScrollPane5.setViewportView(txtDisplayTeams);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 390));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gym.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("Team Information", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        setSize(new java.awt.Dimension(629, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed

    }//GEN-LAST:event_txtLocationActionPerformed

    private void btnAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompActionPerformed
            /**
            * This method collects the information from the user and creates a competition that is stored
            * in the gym's schedule
            */
        
            // Gathering the input from the user entered into the text fields
            String team1 = txtTeam1.getText();
            String team2 = txtTeam2.getText();
            String gameDate = txtCompetitionDate.getText();
            String gameTime = txtCompetitionTime.getText();
            String location = txtLocation.getText();
            
            // Creating the game and adding it to the schedule
            Game game = new Game(team1, team2, gameDate, gameTime, location);
        
            // Testing if any of the text fields are left empty by the user
            if(txtTeam1.getText().isEmpty() || txtTeam2.getText().isEmpty() || txtCompetitionDate.getText().isEmpty() || txtCompetitionTime.getText().isEmpty() || txtLocation.getText().isEmpty()) {
                // Message to the user if any of the text fields were not filled out
                JOptionPane.showMessageDialog(this, "Enter all fields");
            }
       
            // If all the fields are filled out, the information is gathered and placed into a row in the table
            else {
                String[] row = {txtTeam1.getText(), txtTeam2.getText(), txtCompetitionDate.getText(), txtCompetitionTime.getText(), txtLocation.getText()};
                // Table to display the competitions to the user
                DefaultTableModel model = (DefaultTableModel)tblDisplayComps.getModel();
                // Information is added to the table
                model.addRow(row);
            
                // Message to the user that the game scheduling was successful
                JOptionPane.showMessageDialog(this, "Game added");
            }       
    }//GEN-LAST:event_btnAddCompActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Table to display the games
        DefaultTableModel model = (DefaultTableModel)tblDisplayComps.getModel();
        // Array list to store the data from the table
        ArrayList<String> tableData = new ArrayList<>();
        
        // For loop to gather the information from the table row by row and store it in the array list
        for(int i = 0; i < model.getRowCount(); i++) {
            String team1 = model.getValueAt(i, 0).toString();
            String team2 = model.getValueAt(i, 1).toString();
            String gameDate = model.getValueAt(i, 2).toString();
            String gameTime = model.getValueAt(i, 3).toString();
            String location = model.getValueAt(i, 4).toString();
            
            // Data is compiled and added to the array list
            String row = team1 + "," + team2 + "," + gameDate + "," + gameTime + "," + location;
            tableData.add(row);
            
            // try-catch to attempt storing the information in the dat file
            try {
                // Opening the file
                FileOutputStream file = new FileOutputStream("Gym.dat");
                ObjectOutputStream output = new ObjectOutputStream(file);
                
                // Storing the information in the file
                output.writeObject(tableData);
                
                // Closing the files
                output.close();
                file.close();
            }
            // If storing the information is unsuccessful, it catches the error
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // try-catch to place the information stored in the file into the tables
        try {  
            // Opening the file
            FileInputStream file = new FileInputStream("Gym.dat");
            ObjectInputStream input = new ObjectInputStream(file);
            // Adding the information to the array list
            ArrayList<String> tableData = (ArrayList<String>)input.readObject();
        
            // Closing the files
            input.close();
            file.close();
        
            // Table for displaying game schedule
            DefaultTableModel model = (DefaultTableModel)tblDisplayComps.getModel();
            // Adding the information into the table
            for(int i = 0; i < tableData.size(); i++) {
                String[] row = tableData.get(i).split(",");
                model.addRow(row);
            }            
        }
        // If placing the information is unsuccessful, it catches the error
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        /**
         * This method calls the clearFields() method to reset all text fields to be empty
         */
        clearFields();
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void clearFields() {
        /**
         * This method sets all text fields to be empty so the user can schedule another game if they wish 
         */
        txtTeam1.setText("");
        txtTeam2.setText("");
        txtCompetitionDate.setText("");
        txtCompetitionTime.setText("");
        txtLocation.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gym_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gym_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gym_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gym_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gym_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComp;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tblDisplayComps;
    private javax.swing.JTextField txtCompetitionDate;
    private javax.swing.JTextField txtCompetitionTime;
    private javax.swing.JTextArea txtDisplayTeams;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTeam1;
    private javax.swing.JTextField txtTeam2;
    // End of variables declaration//GEN-END:variables
}
