/**
 * CS 234 Stage IV
 * @author Vivian Iracheta-Cruz, Lance Stott, Alena Fisher
 * 5/8/2024
 * This program provides a user-friendly system to manage every aspect of a sports club. The user can add, delete, update, and display
 * information such as appointments, equipment, games, and more.
 */
public class MainMain_GUI extends javax.swing.JFrame {
    // Declaring the sports club
    private Club SportsClub;
    public MainMain_GUI() {
        /**
         * This constructor initializes all components for this file and the sports club
         */
        initComponents();
        SportsClub = new Club();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmployees = new javax.swing.JButton();
        btnFacilities = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnEquipment = new javax.swing.JButton();
        btnMembership = new javax.swing.JButton();
        btnScheduling = new javax.swing.JButton();
        btnCoaches = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmployees.setText("Employee Management");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        btnFacilities.setText("Facilities Management");
        btnFacilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilitiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacilities, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnSales.setText("Sales Management");
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        btnEquipment.setText("Equipment Management");
        btnEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        btnMembership.setText("Membership Management");
        btnMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembershipActionPerformed(evt);
            }
        });
        getContentPane().add(btnMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        btnScheduling.setText("Scheduling Management");
        btnScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchedulingActionPerformed(evt);
            }
        });
        getContentPane().add(btnScheduling, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnCoaches.setText("Coach Management");
        btnCoaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoachesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoaches, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StageIV.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        setSize(new java.awt.Dimension(652, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilitiesActionPerformed
        /**
         * This method passes the sports club as a parameter for the Facilities GUI and opens the window
         */
        new Main_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnFacilitiesActionPerformed

    private void btnSchedulingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchedulingActionPerformed
        /**
         * This method passes the sports club as a parameter for the Appointment GUI and opens the window
         */
        new Appointment_GUI(SportsClub).setVisible(true);  
    }//GEN-LAST:event_btnSchedulingActionPerformed

    private void btnEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipmentActionPerformed
        /**
         * This method passes the sports club as a parameter for the Equipment GUI and opens the window
         */
        new Equipment_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnEquipmentActionPerformed

    private void btnMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembershipActionPerformed
        /**
         * This method passes the sports club as a parameter for the Membership GUI and opens the window
         */
        new MembershipGUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnMembershipActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        /**
         * This method passes the sports club as a parameter for the Employees GUI and opens the window
         */
        new EmployeeManagementGUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnCoachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoachesActionPerformed
        /**
         * This method passes the sports club as a parameter for the Coaches GUI and opens the window
         */
        new Coaches_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnCoachesActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        /**
         * This method passes the sports club as a parameter for the Sales GUI and opens the window
         */
        new MainGUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnSalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMain_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMain_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMain_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMain_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMain_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoaches;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnEquipment;
    private javax.swing.JButton btnFacilities;
    private javax.swing.JButton btnMembership;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnScheduling;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
