/**
 * @author  Alena Fisher
 * 5/7/2024
 */

public class Main_GUI extends javax.swing.JFrame {
    // Declaring the variables for sports club and the hockey teams
    private Club SportsClub;
    private Teams Hockeyteams;

    public Main_GUI() {
        /**
         * This constructor initializes the components for the file and the Sports Club and the list for the hockey teams
         */
        initComponents();
        SportsClub = new Club();
        Hockeyteams = new Teams();
        
        // Adding teams to the list
        Team carolinaHurricanes = new Team("Carolina Hurricanes", "Rod Brind'Amour", "Raleigh", "North Carolina", "26");
        Hockeyteams.addTeam(carolinaHurricanes);
        
        Team coloradoAvalanche = new Team("Colorado Avalanche", "Jared Bednar", "Denver", "Colorado", "23");
        Hockeyteams.addTeam(coloradoAvalanche);

        Team nmIceWolves = new Team("New Mexico Ice Wolves", "Phil Fox", "Albuquerque", "New Mexico", "30");
        Hockeyteams.addTeam(nmIceWolves);

        Team minnesotaWild = new Team("Minnesota Wild", "John Hynes", "St. Paul", "Minnesota", "27");
        Hockeyteams.addTeam(minnesotaWild);

        Team seattleKraken = new Team("Seattle Kraken", "Dave Hakstol", "Seattle", "Washington", "22");
        Hockeyteams.addTeam(seattleKraken);
    }
    
    public Main_GUI(Club aClub) {
        /**
         * This constructor receives 'aClub' as an explicit parameter and creates an object for the window to be opened
         */
        this();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnField = new javax.swing.JButton();
        btnGym = new javax.swing.JButton();
        btnCourt = new javax.swing.JButton();
        btnIceRink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setTitle("Main Screen");

        btnField.setText("Field");
        btnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldActionPerformed(evt);
            }
        });

        btnGym.setText("Gym");
        btnGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGymActionPerformed(evt);
            }
        });

        btnCourt.setText("Court");
        btnCourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourtActionPerformed(evt);
            }
        });

        btnIceRink.setText("Ice Rink");
        btnIceRink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIceRinkActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/StageIV.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(btnGym))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCourt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(btnIceRink))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnGym)
                        .addGap(197, 197, 197)
                        .addComponent(btnCourt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(btnIceRink))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldActionPerformed
        /**
         * This method passes the sports club as a parameter for the Field GUI and opens the window
         */
        new Field_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnFieldActionPerformed

    private void btnGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGymActionPerformed
        /**
         * This method passes the sports club as a parameter for the Gym GUI and opens the window
         */
        new Gym_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnGymActionPerformed

    private void btnCourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourtActionPerformed
        /**
         * This method passes the sports club as a parameter for the Court GUI and opens the window
         */
        new Court_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnCourtActionPerformed

    private void btnIceRinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIceRinkActionPerformed
        /**
         * This method passes the sports club as a parameter for the Ice Rink GUI and opens the window
         */
        new Rink_GUI(SportsClub).setVisible(true);
    }//GEN-LAST:event_btnIceRinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourt;
    private javax.swing.JButton btnField;
    private javax.swing.JButton btnGym;
    private javax.swing.JButton btnIceRink;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
