

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexi
 */
public class Sales_GUI extends javax.swing.JFrame {
    SalesManager mySalesM;
    static String fileLocation = "inventory.dat";
    static String fileLocation1 = "viewsales.dat";
    
    
   
    

    /**
     * Creates new form Sales_GUI
     */
    public Sales_GUI() {
        mySalesM = new SalesManager();
        initComponents();
        billHeader();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //Method that automatically prints info on the receipt
    private void billHeader() {
            Date obj = new Date();
            String date = obj.toString();

            txtReceipt.setText("\t\t\t\tPortales Sports Center" + "\n\t\t\t\tPortales, New Mexico" + "\n\n\t\t\t\t\tRECEIPT" +  
                    "\n\n" + date + "\n\n\n\tDescription" + "\t\t\tPrice" + "\t\t\tQty");
        }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelSale = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmployee = new javax.swing.JTextField();
        txtSaleID = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        labelCart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lbSubtotal = new javax.swing.JLabel();
        txtPoints = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        labelProduct = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        panelReceipt = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblViewSales = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtView = new javax.swing.JTextField();
        btnViewSearch = new javax.swing.JButton();
        btnViewClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panelSale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Sale ID");
        panelSale.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setText("Employee");
        panelSale.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setText("Customer");
        panelSale.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        panelSale.add(txtEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, -1));
        panelSale.add(txtSaleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, -1));
        panelSale.add(txtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, -1));
        panelSale.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, -1));

        labelCart.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        labelCart.setText("Cart");
        panelSale.add(labelCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);

        panelSale.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 310, 280));

        jLabel8.setText("Phone #");
        panelSale.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnDelete.setText("Delete Item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelSale.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        btnComplete.setText("Complete Sale");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        panelSale.add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtTotal.setEditable(false);
        panelSale.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 71, -1));

        txtDiscount.setEditable(false);
        panelSale.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 71, -1));

        lbTotal.setText("Total");
        panelSale.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        lbDiscount.setText("Discount");
        panelSale.add(lbDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        panelSale.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 71, -1));

        lbSubtotal.setText("SubTotal");
        panelSale.add(lbSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));
        panelSale.add(txtPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 100, -1));

        jLabel4.setText("Loyalty Points");
        panelSale.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Sale"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbID.setText("Item ID:");
        jPanel1.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 71, -1));

        btnClear.setText("Clear Sale");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        btnAdd.setText("Add to Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 198, 71, -1));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 71, -1));

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 71, -1));

        jLabel1.setText("Price");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, -1));

        panelSale.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 320, 150));

        labelProduct.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        labelProduct.setText("Product Log");
        panelSale.add(labelProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        panelSale.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 390, 440));

        jTabbedPane2.addTab("Sale", panelSale);

        panelReceipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane3.setViewportView(txtReceipt);

        panelReceipt.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 750, 410));

        jTabbedPane2.addTab("Receipt", panelReceipt);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Search by Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tblViewSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale ID", "Employee", "Customer", "Phone #", "Total"
            }
        ));
        jScrollPane4.setViewportView(tblViewSales);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel10.setText("Past Sales");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        txtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewActionPerformed(evt);
            }
        });
        jPanel2.add(txtView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        btnViewSearch.setText("Search");
        btnViewSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        btnViewClear.setText("Clear");
        btnViewClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jTabbedPane2.addTab("View Sales", jPanel2);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 960, 530));

        setSize(new java.awt.Dimension(975, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //Calls the clear fields method to set all the text fields to empty when pushed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       Sale sale = new Sales(id, name, price, quantity);
       mySalesM.addSale(sale);
        
        
        //Checks if all the text boxes are empty and if they aren't then it takes the information and adds it to the recepit
        if(txtID.getText().isEmpty()|| txtItemName.getText().isEmpty() || txtPrice.getText().isEmpty() || txtQty.getText().isEmpty()
                || txtItemName.getText().isEmpty() || txtPrice.getText().isEmpty() ||txtQty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all fields");
        }
        else {
            String[] row = {txtID.getText(), txtItemName.getText(), txtPrice.getText(), txtQty.getText()};
            DefaultTableModel model = (DefaultTableModel)tblCart.getModel();
            model.addRow(row);

                        
            txtReceipt.setText(txtReceipt.getText() + "\n\n\t" + txtItemName.getText()
                        + "\t\t\t" + txtPrice.getText() + "\t\t\t" + txtQty.getText());
            
            
              
            JOptionPane.showMessageDialog(this, "Information added");
            
            clearFields();
        }
    
    }//GEN-LAST:event_btnAddActionPerformed

    //Sets all the text fields to empty
    private void clearFields() {
        txtID.setText("");
        txtItemName.setText("");
        txtPrice.setText("");
        txtQty.setText("");
        txtSubtotal.setText("");
        txtDiscount.setText("");
        txtTotal.setText("");
        txtPoints.setText("");
        txtView.setText("");
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       //Deletes the selected row from the Cart table
        int row = tblCart.getSelectedRow();

        if(row < 0) {
            JOptionPane.showMessageDialog(this, "You need to select a row");
        }
        else {
            DefaultTableModel model = (DefaultTableModel)tblCart.getModel();
            model.removeRow(row);
            JOptionPane.showMessageDialog(this, "Item deleted");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        
    }//GEN-LAST:event_txtIDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Loads all the saved data from the Inventory into the Product table
        
        try {
            System.out.println("Reading in data");
            FileInputStream file = new FileInputStream("inventory.dat");
            ObjectInputStream input = new ObjectInputStream(file);
            ArrayList<String> tableData = (ArrayList<String>)input.readObject();
            
            input.close();
            file.close();
            
            DefaultTableModel model = (DefaultTableModel)tblProduct.getModel();
            for(int i=0; i<tableData.size(); i++)
            {
                String[] row = tableData.get(i).split(",");
                model.addRow(row);
            }
            JOptionPane.showMessageDialog(this, "Data loaded successfully");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        //Loads all saved data from Sale in the View Sales table
        try {
            System.out.println("Reading in data");
            FileInputStream file1 = new FileInputStream("viewsales.dat");
            ObjectInputStream input1 = new ObjectInputStream(file1);
            ArrayList<String> tableData1 = (ArrayList<String>)input1.readObject();
            
            input1.close();
            file1.close();
            
            DefaultTableModel model1 = (DefaultTableModel)tblViewSales.getModel();
            for(int i=0; i<tableData1.size(); i++)
            {
                String[] row = tableData1.get(i).split(",");
                model1.addRow(row);
            }
            JOptionPane.showMessageDialog(this, "Sales loaded successfully");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Saves any changes that may have happened in the Product table when closed
        
        DefaultTableModel model = (DefaultTableModel)tblProduct.getModel();
        
        ArrayList<String> tableData = new ArrayList<>();
        
        for(int i=0; i<model.getRowCount();i++)
        {  
            String id = model.getValueAt(i, 0).toString();
            String name = model.getValueAt(i, 1).toString();
            String price = model.getValueAt(i, 2).toString();
            String quantity = model.getValueAt(i, 3).toString();
            
            String row = id + "," + name + "," + price + "," + quantity;
            tableData.add(row);
            System.out.println(row);
        }
       
       
        try{
            FileOutputStream file = new FileOutputStream("inventory.dat");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            output.writeObject(tableData);
            
            output.close();
            file.close();

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        //Save any changes that happened in the ViewSales table when closed
        DefaultTableModel model1 = (DefaultTableModel)tblViewSales.getModel();
        
        ArrayList<String> tableData1 = new ArrayList<>();
        
        for(int i=0; i<model1.getRowCount();i++)
        {  
            String id = model1.getValueAt(i, 0).toString();
            String employee = model1.getValueAt(i, 1).toString();
            String customer = model1.getValueAt(i, 2).toString();
            String phone = model1.getValueAt(i, 3).toString();
            String total = model1.getValueAt(i, 4).toString();
            
            
            String row1 = id + "," + employee + "," + customer + "," + phone + "," + total;
            tableData1.add(row1);
            System.out.println(row1);
        }
       
    
        try{
            FileOutputStream file1 = new FileOutputStream("viewsales.dat");
            ObjectOutputStream output1 = new ObjectOutputStream(file1);
            
            output1.writeObject(tableData1);
            
            output1.close();
            file1.close();

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
       //Adds the information from the Product table to the new sale text fields
       DefaultTableModel model = (DefaultTableModel)tblProduct.getModel();
       int selectedRowIndex = tblProduct.getSelectedRow();
       
       txtID.setText(model.getValueAt(selectedRowIndex, 0).toString());
       txtItemName.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txtPrice.setText(model.getValueAt(selectedRowIndex, 2).toString());
       txtQty.setText(model.getValueAt(selectedRowIndex, 3).toString());
       
    }//GEN-LAST:event_tblProductMouseClicked

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        //Calculates the subtotal and total and checks to see if they added loyalty points for a discount
        
        int numrow = tblCart.getRowCount();
        
        float tot = 0;
        
        if( txtPoints.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Loyalty Points");
        } else {
            for(int i = 0; i < numrow; i++) {
            float value = Float.parseFloat(tblCart.getValueAt((int)i,2).toString()) * Float.parseFloat(tblCart.getValueAt((int)i,3).toString());
            tot += value;
            int points = Integer.parseInt(txtPoints.getText());
            double discount = points * 0.01;
            double sub = tot;
            double total = sub - discount;
            txtSubtotal.setText("$" + sub);
            txtDiscount.setText("$" + discount);
            txtTotal.setText("$" + total);
           
        
            }
            //Prints this on the receipt
             txtReceipt.setText( txtReceipt.getText() +"\n\n\nCasher: " +txtEmployee.getText() 
                        + "\nSale ID: " + txtSaleID.getText() + "\n\t\t\t\t\t\tSubtotal: " + txtSubtotal.getText()
                            +"\n\n\t\t\t\t\t\tLoyalty Points Used: " + txtPoints.getText() +  "\n\n\t\t\t\t\t\tDiscount: " + txtDiscount.getText()
                                +"\n\n\t\t\t\t\t\tTotal: " + txtTotal.getText());
        }
        
        //Prints on the ViewSales table
        if(txtSaleID.getText().isEmpty()|| txtEmployee.getText().isEmpty() || txtCustomer.getText().isEmpty() || txtPhone.getText().isEmpty()
                || txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all fields");
        }
        else {
            String[] row = {txtSaleID.getText(), txtEmployee.getText(), txtCustomer.getText(), txtPhone.getText(), txtTotal.getText()};
            DefaultTableModel model = (DefaultTableModel)tblViewSales.getModel();
            model.addRow(row);
           
        }
        
        
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    //Used to search in the ViewSales table
    private void findView() {
        
        DefaultTableModel sorter = (DefaultTableModel)tblViewSales.getModel();
        TableRowSorter<DefaultTableModel> sorter1 = new TableRowSorter<>(sorter);
        tblViewSales.setRowSorter(sorter1);
        sorter1.setRowFilter(RowFilter.regexFilter(txtView.getText()));
        
    }
    private void btnViewSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSearchActionPerformed
       String id = txtSaleID.getText();
       boolean found = (int)Integer.parseInt(mySalesM.findSale(id).toString());
        
        findView();
        clearFields();
    }//GEN-LAST:event_btnViewSearchActionPerformed

    private void btnViewClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewClearActionPerformed
        findView();
        clearFields();
    }//GEN-LAST:event_btnViewClearActionPerformed

    private void txtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewActionPerformed
        findView();
    }//GEN-LAST:event_txtViewActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewClear;
    private javax.swing.JButton btnViewSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelCart;
    private javax.swing.JLabel labelProduct;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel panelReceipt;
    private javax.swing.JPanel panelSale;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblViewSales;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPoints;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtSaleID;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtView;
    // End of variables declaration//GEN-END:variables
}
